apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-translator-deployment
  labels:
    app: webhook-translator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-translator
  template:
    metadata:
      labels:
        app: webhook-translator
    spec:
      containers:
      - name: webhook-translator
        image: webhook-translator:latest
        ports:
        - containerPort: 5000
        env:
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: openai-secret
              key: api_key
        - name: OPENAI_URL
          value: "https://api.openai.com/v1/engines/davinci/completions"
        - name: OPSGENIE_API_KEY
          valueFrom:
            secretKeyRef:
              name: opsgenie-secret
              key: api_key
        - name: OPSGENIE_URL
          value: "https://api.opsgenie.com/v2/alerts"
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 15
